# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Publish

# Trigger the workflow's on pushed version tags.
on:
  push:
    tags: "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  # Builds and pushes docker images to DockerHub and package the Helm chart and
  # pushes it to jupyterhub/helm-chart@gh-pages where index.yaml represents the
  # JupyterHub organization Helm chart repository.
  #
  # ref: https://github.com/jupyterhub/helm-chart
  # ref: https://hub.docker.com/orgs/jupyterhub
  #
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -alh dist

      # ref: https://github.com/pypa/gh-action-pypi-publish
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
