# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Tests

# Trigger the workflow's on pushed branches or commits to main/master branch.
on:
  pull_request:
  push:

defaults:
  run:
    # Declare bash be used by default in this workflow's "run" steps.
    #
    # NOTE: bash will by default run with:
    #   --noprofile: Ignore ~/.profile etc.
    #   --norc:      Ignore ~/.bashrc etc.
    #   -e:          Exit directly on errors
    #   -o pipefail: Don't mask errors from a command piped into another command
    shell: bash

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        # We run this job multiple times with different parameterization
        # specified below, these parameters have no meaning on their own and
        # gain meaning on how job steps use them.
        #
        # k3s-version: https://github.com/rancher/k3s/tags
        include:
          - python: 3.6
          - python: 3.7
          - python: 3.8
          - python: 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install package and development dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install -r dev-requirements.txt
          pip freeze

      - name: Run pytest
        run: |
          pytest --verbose --flakes
